### ISSUE TITLE
Adicionar link para a Wiki na descrição do projeto

### ISSUE THREAD

**Issue by ricardovigatti** [matheusfrade/casaolec-calculadora#2]
@matheusfrade , se possível, favor adicionar o link https://github.com/matheusfrade/casaolec-calculadora/wiki na descrição do projeto, que hoje encontra-se em branco.

![image](https://user-images.githubusercontent.com/1699931/35526004-1dd27862-051e-11e8-87f7-7ada164e6632.png)

Obrigado.

**Comment by matheusfrade** [comment]
Coloquei lá, veja se é isso mesmo porque não conheço vários recursos ainda aqui do Github.

**Comment by ricardovigatti** [comment]
Sim, é isso mesmo. É só pra facilitar a encontrar essa informação. Obrigado.
